### ISSUE TITLE
docker 镜像启动失败

### ISSUE THREAD

**Issue by hklinux2010** [elroy93/12306spy#9]
Traceback (most recent call last):
  File "/app/main.py", line 8, in <module>
    from query_any_seat import query_any_seat
  File "/app/query_any_seat.py", line 4, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.12/site-packages/pandas/__init__.py", line 14, in <module>
    __import__(_dependency)
  File "/usr/local/lib/python3.12/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/usr/local/lib/python3.12/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/usr/local/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/local/lib/python3.12/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 463, in _lock_unlock_module
KeyboardInterrupt

**Comment by e1roy** [comment]
从日志看是手动停止的， 建议重新启动一下。
